cinema/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('worker/', include('worker.urls')),
    path('', include('client.urls')),
]

#if settings.DEBUG:
    #urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

client/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.IndexMovieListView.as_view(), name='index-client'),
    path('cennik/', views.cennik, name='price-list-client'),
    path('kontakt/', views.kontakt, name='contact-client'),
    path('okinie/', views.okinie, name='about-client'),
    path('repertuar/', views.RepertuarShowtimeListView.as_view(), name='repertoire-list-client'),

    # film
    path('film/<int:pk>', views.FilmMovieDetailView.as_view(), name='movie-details-client'),

    # rezerwacja
    path('rezerwuj-miejsce/<int:showtime_id>', views.reservation_form, name='reservation-form-client'),
    path('bilety/', views.ticket_types_client, name='reservation-tickets-client'),
    path('podsumowanie/', views.summary_client, name='summary-client'),

    # rezerwacje - decyzje
    # https://stackoverflow.com/questions/32950432/django-urls-uuid-not-working
    path('potwierdz/<uuid:id>', views.rezerwacja_potwierdz, name='reservation-accept-client'),
    path('anuluj/<uuid:id>', views.rezerwacja_anuluj, name='reservation-deny-client'),
]

client/models.py
from django.db import models

# Create your models here.

worker/models.py
import uuid
from django.db import models
from django.urls import reverse
import datetime
from django.utils import timezone
from PIL import Image


class Client(models.Model):
    client_id = models.AutoField(primary_key=True, null=False)
    first_name = models.CharField(max_length=55)
    last_name = models.CharField(max_length=55)
    email = models.EmailField(max_length=255)
    phone_number = models.CharField(max_length=15, null=True)

    def __str__(self):
        name = str(self.first_name) + ' ' + str(self.last_name)
        return name

    def get_absolute_url(self):
        return reverse('worker:worker-client-details', kwargs={'client_id': self.client_id})


class Movie(models.Model):
    movie_id = models.AutoField(primary_key=True, null=False)
    title = models.CharField(max_length=255)
    director = models.CharField(max_length=255)
    release_date = models.IntegerField()
    duration = models.DurationField(null=False)
    description = models.TextField(null=True)
    link = models.URLField(max_length=255, null=True)
    thumbnail = models.ImageField(default='', upload_to='images', max_length=255)
    trailer_youtube_id = models.CharField(max_length=255, null=True)
    deleted = models.BooleanField(default=False)

    # adres pod który zostaniemy przekierowani po dodaniu filmu do bazy (klasa MovieCreateView)
    # w tym przypadku przenosi nas do szczegolow dodanego filmu
    def get_absolute_url(self):
        return reverse('movie-details-worker', kwargs={'pk': self.movie_id})

    def __str__(self):
        return self.title


class Seat(models.Model):
    seat_id = models.AutoField(primary_key=True)
    seat_number = models.IntegerField(null=True)
    row_number = models.CharField(null=True, max_length=1)

    def __str__(self):
        return str(self.row_number) + '' + str(self.seat_number)


class Showtime(models.Model):
    showtime_id = models.AutoField(primary_key=True, null=False)
    movie_id = models.ForeignKey(Movie, on_delete=models.PROTECT)
    start_date = models.DateTimeField(null=True)
    show_break = models.DurationField(default=0)
    end_date = models.DateTimeField(null=True, editable=False)

    # nadpisana metoda zapisu, ktora na podstawie trwania filmu okresla czas jego zakonczenia + przerwa po seansie
    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.end_date = self.start_date + datetime.timedelta(
            seconds=self.movie_id.duration.seconds) + datetime.timedelta(
            seconds=self.show_break.seconds)
        super(Showtime, self).save()

    # adres pod który zostaniemy przekierowani po dodaniu seansu do bazy (klasa ShowtimeCreateView)
    # w tym przypadku przenosi nas do szczegolow dodanego seansu
    def get_absolute_url(self):
        return reverse('showtime-details-worker', kwargs={'pk': self.showtime_id})

    def __str__(self):
        return str(self.movie_id.title) + ' - ' + str(self.start_date)


class TicketType(models.Model):
    ticket_id = models.AutoField(primary_key=True, null=False)
    type = models.CharField(max_length=40)
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    conditions = models.TextField(null=True)
    deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.type


class Ticket(models.Model):
    ticket_id = models.AutoField(primary_key=True, null=False)
    client_id = models.ForeignKey(Client, on_delete=models.CASCADE)
    tickettype_id = models.ForeignKey(TicketType, on_delete=models.PROTECT)
    seat_id = models.ForeignKey(Seat, on_delete=models.PROTECT)
    showtime_id = models.ForeignKey(Showtime, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True)

    def __str__(self):
        return str(self.ticket_id) + '. ' + self.client_id.first_name + \
               ' ' + self.client_id.last_name + ' - ' + self.showtime_id.movie_id.title + ' - ' \
               + str(self.showtime_id.start_date)


class Reservation(models.Model):
    reservation_id = models.AutoField(primary_key=True, null=False)
    client_id = models.ForeignKey(Client, on_delete=models.CASCADE)
    showtime_id = models.ForeignKey(Showtime, on_delete=models.CASCADE)
    cost = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    paid = models.BooleanField(default=False)
    ticket_id = models.ManyToManyField(Ticket)
    reservation_date = models.DateTimeField(null=True)
    reservation_expire = models.DateTimeField(null=True)
    confirmed = models.BooleanField(default=False)
    # https://stackoverflow.com/questions/16925129/generate-unique-id-in-django-from-a-model-field
    reservation_confirmation_code = models.UUIDField(primary_key=False, default=uuid.uuid4, editable=False)
    confirmation_email = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('reservation-details-worker', kwargs={'pk': self.reservation_id})

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.reservation_date = timezone.now()
        self.reservation_expire = self.reservation_date + timezone.timedelta(minutes=30)  # rezerwacja wygasa po 30min
        return super(Reservation, self).save()

    def __str__(self):
        return str(self.reservation_id) + '. ' + str(self.client_id.first_name) + ' ' + str(
            self.client_id.last_name) + ' - ' + str(self.showtime_id.movie_id.title) + ' - ' \
               + str(self.showtime_id.start_date)

client/views.py
import django.forms
from django.core.mail import send_mail
from django.db import transaction
from django.forms import modelformset_factory
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView
from worker.models import *
from . import forms
# nalezy uzywac metody timezone.now(),
# aby wyeliminowac problem "RuntimeWarning: DateTimeField Showtime.start_date received a naive datetime
# while time zone support is active."
from django.utils import timezone
from cinema.settings import EMAIL_HOST_USER
from django.template import loader
from django.contrib import messages
from django.shortcuts import get_object_or_404


class IndexMovieListView(ListView):
    template_name = 'client/index.html'
    model = Movie

    # wyswietla tylko filmy, ktorych seans zaczyna sie w przyszlosci
    # ukrywa filmy, ktore nie maja seansu, oraz te, ktorych czas rozpoczecia juz minal
    # eliminuje duplikaty w przypadku dodania wiecej niz jednego filmu
    pass

    # queryset = Movie.objects.filter(movie_id__in=Showtime.objects.all(),
    #                                 showtime__start_date__gt=timezone.now()).distinct()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(IndexMovieListView, self).get_context_data(**kwargs)

        # obecny czas w strefie czasowej CET
        tz_now = timezone.now()
        # context['events'] = Event.objects.all()  # todo dodac sortowanie wg daty
        # wyswietla filmy ktore sa grane dzisiaj,
        # oraz data rozpoczecia jest w przyszlosci - czyli od obecnej godziny do północy
        # context['today'] = Movie.objects.filter(showtime__start_date__day=tz_now.day,
        #                                         showtime__start_date__gte=tz_now).distinct()
        context['today'] = Movie.objects.filter(showtime__start_date__day=tz_now.day,
                                                showtime__start_date__gte=tz_now).distinct()
        # jutrzejszy dzień  - godzina 00:00:00
        tomorrow = tz_now - timezone.timedelta(hours=tz_now.hour,
                                               minutes=tz_now.minute,
                                               seconds=tz_now.second) + timezone.timedelta(days=1)
        # data "za dwa tygodnie"
        two_weeks = tz_now + timezone.timedelta(days=14)

        context['future'] = Movie.objects.filter(movie_id__in=Showtime.objects.values('movie_id'),
                                                 showtime__start_date__gt=tomorrow, showtime__end_date__lte=two_weeks). \
            distinct('movie_id')

        return context


class FilmMovieDetailView(DetailView):
    template_name = 'client/film.html'
    model = Movie

    # wyswietla tylko filmy, ktorych seans zaczyna sie w przyszlosci, sortuje po dacie rozpoczecia
    def get_context_data(self, **kwargs):
        context = super(FilmMovieDetailView, self).get_context_data(**kwargs)
        context['showtime'] = Showtime.objects.filter(movie_id=self.get_object(),
                                                      start_date__gte=timezone.now()).order_by('start_date')
        return context


def reservation_form(request, **kwargs):  # kwargs przekazywanie z urls
    time_now = timezone.now()
    showtime_id = kwargs['showtime_id']
    showtime = Showtime.objects.get(showtime_id=showtime_id)
    # pass initial data to form https://www.geeksforgeeks.org/initial-form-data-django-forms/
    initial = {'showtime_id': showtime_id}

    r_form = forms.ReservationModelForm(initial=initial)
    client_form = forms.ClientModelForm()

    # lista zajetych siedzien
    taken_seats = Ticket.objects.filter(showtime_id=showtime_id).values_list('seat_id', flat=True)

    s_form = forms.SeatForm(taken_seats=taken_seats)

    # siedzenia wolne
    seats = Seat.objects
    seats_row_a = seats.filter(row_number='A')
    seats_row_b = seats.filter(row_number='B')
    seats_row_c = seats.filter(row_number='C')
    seats_row_d = seats.filter(row_number='D')
    seats_row_e = seats.filter(row_number='E')
    seats_row_f = seats.filter(row_number='F')
    seats_row_g = seats.filter(row_number='G')
    seats_row_h = seats.filter(row_number='H')
    seats_row_i = seats.filter(row_number='I')
    seats_row_j = seats.filter(row_number='J')

    if request.POST:
        taken = []
        for i in request.POST.lists():
            if i[0].startswith('seats_row_'):
                taken.extend(i[1])

        r_form = forms.ReservationModelForm(request.POST)
        r_form.fields['showtime_id'].widget = r_form.fields['showtime_id'].hidden_widget()
        client_form = forms.ClientModelForm(request.POST)

        if client_form.is_valid() and r_form.is_valid():
            request.session['taken'] = taken
            request.session['data'] = request.POST

            if len(taken) > 10:
                messages.add_message(request, messages.ERROR, 'Możesz zarezerwować maksymalnie 10 miejsc!')
            else:
                return redirect('reservation-tickets-client')

    return render(request, 'client/rezerwacja_na_seans.html', context={'showtime_id': showtime_id,
                                                                       'showtime': showtime,
                                                                       'client_form': client_form,
                                                                       'reservation_form': r_form,
                                                                       'seats_row_a': seats_row_a,
                                                                       'seats_row_b': seats_row_b,
                                                                       'seats_row_c': seats_row_c,
                                                                       'seats_row_d': seats_row_d,
                                                                       'seats_row_e': seats_row_e,
                                                                       'seats_row_f': seats_row_f,
                                                                       'seats_row_g': seats_row_g,
                                                                       'seats_row_h': seats_row_h,
                                                                       'seats_row_i': seats_row_i,
                                                                       'seats_row_j': seats_row_j,
                                                                       'taken_seats': taken_seats,
                                                                       's_form': s_form,
                                                                       'time_now': time_now})


def ticket_types_client(request, **kwargs):
    if 'data' in request.session:
        taken = request.session.get('taken')
        data = request.session.get('data')
        showtime_id = data['showtime_id']

        paid = data['paid'] if data.get('paid') else ''
        confirmed = data['confirmed'] if data.get('confirmed') else ''

        reservation_initial = {'showtime_id': data['showtime_id'],
                               'confirmed': confirmed,
                               'paid': paid}

        client_initial = {'first_name': data['first_name'],
                          'last_name': data['last_name'],
                          'email': data['email'],
                          'phone_number': data['phone_number']}

        showtime = Showtime.objects.get(showtime_id=showtime_id)

        r_form = forms.ReservationModelForm(initial=reservation_initial)
        r_form.fields['showtime_id'].widget = r_form.fields['showtime_id'].hidden_widget()

        client_form = forms.ClientModelForm(initial=client_initial)
        client_form.fields['first_name'].widget = client_form.fields['first_name'].hidden_widget()
        client_form.fields['last_name'].widget = client_form.fields['last_name'].hidden_widget()
        client_form.fields['email'].widget = client_form.fields['email'].hidden_widget()
        client_form.fields['phone_number'].widget = client_form.fields['phone_number'].hidden_widget()

        ticket_formset = modelformset_factory(Ticket,
                                              fields=('seat_id', 'tickettype_id'),
                                              labels={'seat_id': '',
                                                      'tickettype_id': 'Typ Biletu'},
                                              extra=len(taken),
                                              widgets={'seat_id': django.forms.Select(attrs={'hidden': ''})},
                                              max_num=10)

        ticket_form = ticket_formset(queryset=Ticket.objects.none(), initial=[{'seat_id': z} for z in taken])

        # pokazuje tylko typy biletów, które nie są usunięte
        for form in ticket_form:
            form.fields['tickettype_id'].queryset = TicketType.objects.filter(deleted=False)

        if request.POST:
            r_form = forms.ReservationModelForm(request.POST)
            client_form = forms.ClientModelForm(request.POST)
            ticket_form = ticket_formset(request.POST)

            # pokazuje tylko typy biletów, które nie są usunięte
            for form in ticket_form:
                form.fields['tickettype_id'].queryset = TicketType.objects.filter(deleted=False)

            r_form.fields['showtime_id'].widget = r_form.fields['showtime_id'].hidden_widget()
            client_form.fields['first_name'].widget = client_form.fields['first_name'].hidden_widget()
            client_form.fields['last_name'].widget = client_form.fields['last_name'].hidden_widget()
            client_form.fields['email'].widget = client_form.fields['email'].hidden_widget()
            client_form.fields['phone_number'].widget = client_form.fields['phone_number'].hidden_widget()

            if ticket_form.is_valid() and (client_form.is_valid() and r_form.is_valid()):

client/templates/client/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'client/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    {% block head %}
    {% endblock %}
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Nova+Round&display=swap">
    <style>
    body {
    background: url({% static 'client/images/back1.jpg' %}) no-repeat center center fixed;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    background-size: cover;
    -o-background-size: cover;
    }
    .container{
        font-family: 'Nova Round', cursive;
        font-size: 25px;
        letter-spacing: 0.5px;
    }

</style>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</head>
<body>
<nav class="navbar navbar-expand-lg py-3 navbar-dark bg-dark">
<div class="container">
    <a href="#" class="navbar-brand">
    <img src="{% static 'client/images/logo.png' %}" class="logo">
        </a>


    {% block logo-text %}
    {% endblock %}
   <div id="navbarMenu" class="collapse navbar-collapse">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item-active"><a href="{% url 'index-client' %}" class="nav-link">Strona główna &nbsp</a></li>
            <li class="nav-item"><a href="{% url 'repertoire-list-client' %}" class="nav-link">Repertuar &nbsp</a></li>
            <li class="nav-item"><a href="{% url 'price-list-client' %}" class="nav-link">Cennik &nbsp</a></li>
            <li class="nav-item"><a href="{% url 'about-client' %}" class="nav-link">O kinie &nbsp</a></li>
            <li class="nav-item"><a href="{% url 'contact-client' %}" class="nav-link">Kontakt &nbsp</a></li>
        </ul>
    </div>
</div>
</nav>
<br>
<div class="container-bg">

{% block content %}
{% endblock %}
</div>
</body>
</html>

client/templates/client/cennik.html
{% extends 'client/base.html' %}
{% load static %}
{% block head %}
    <title>Cennik</title>
    <style>
        .table {
            width: 100%;
            border-collapse: collapse;
            border-spacing: 0;
            margin-bottom: 1%;
        }

        .table td,
        th {
            font-size: 25px;
            border-top: 1px solid #ddd;
            padding: 5px 12px;
            text-align: left;
            vertical-align: top;
        }




        h2 {
            margin-top: 5%;
        }



        a:hover {
            color: #fff;
        }
    </style>
{% endblock %}

{% block logo-text %}
    <h1 class="logo-text">Cennik</h1>
{% endblock %}
{% block content %}
    <br>
    <br>

   <table class="table table-striped table-dark">
        <thead>
        <tr>
            <th scope="col">Typ</th>
            <th scope="col">Cena</th>
        </tr>
        </thead>
        <tbody>
        {% for ticket in ticket_types %}
            <tr>
                <td><strong>{{ ticket.type }}</strong></td>
                <td><strong>{{ ticket.price }}</strong></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <br><br><br>


        <div class="card text-center" style="15 padding: 10px; border:20px;margin-left: 100px; margin-top:30px; background: darkgray; opacity: 90%; margin-bottom: 200px; width:50rem;">
<div class="card-body" style="font-size:18px">
    {% for ticket in ticket_types %}
        {{ ticket.type }} - {{ ticket.conditions }}<br>
    {% endfor %}
  </div>
    </div>
{% endblock %}r

client/templates/client/film.html
{% extends 'client/base.html' %}
{% block head %}
    <title>{{ object.title }}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
{% endblock %}

{% block content %}
<div class="card" style="width: 50rem; padding:25px;margin-left:400px;box-shadow:0 10px 6px -20px black; margin-bottom: 10px; background-color: #d8d8d8; opacity: 90%">
    {% if messages %}
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    {% endif %}
    <img src="{{ object.thumbnail.url }}" width="200" height="285" style="margin-left: 250px"/><br>
    <b>tytuł:</b>  {{ object.title|title }}<br><br>
    <b>reżyser:</b> {{ object.director }}<br>
    <b>data premiery:</b> {{ object.release_date }}<br>
    <b>czas trwania:</b> {{ object.duration }}<br><br>
    {{ object.description }}<br><br>
    {% if object.trailer_youtube_id %}
        <iframe width="560" height="315" src="https://www.youtube.com/embed/{{ object.trailer_youtube_id }}"
                frameborder="0"
                allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                allowfullscreen></iframe>
    {% endif %}
<div class="card-text">
    <br><br>
    Recenzje, oraz opinie o filmie znajdują się <a class="btn btn-default" href="{{ object.link }}"><b class="btn btn-primary">tutaj</b></a>
    <br><br>
</div>
    Najbliższe seanse:<br>
    {% if showtime %}
        {% for x in showtime %}
            {{ x.start_date| date:"d.m.Y H:i" }}
            <a class="btn btn-info" style="width:10rem;margin-left: 300px " href="{% url 'reservation-form-client' x.showtime_id %}">Zarezerwuj miejsce</a><br>
        {% endfor %}
    {% else %}
        <b>Przepraszamy, wybrany film nie jest obecnie wyświetlany.</b>
    {% endif %}
</div>
{% endblock %}

client/templates/client/index.html
{% extends 'client/base.html' %}

{% block head %}
    <title>Kino MovieCity</title>
{% endblock %}


{% block logo-text %}
    <h1 class="logo-text">MOVIE CITY</h1>
{% endblock %}

{% block content %}
    {{ MEDIA_URL }}
    {% if messages %}
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    {% endif %}

    {% if object_list|length > 0 %}
        <div class="container series">
            {% if today|length > 0 %}
                <h2>Dzisiaj gramy:</h2>
                <div class="row">
                <div class="col-md-4">
                    <br>
                    {% for d in today %}
                        <div class="row">
                            <div class="col-6"><a href="{% url 'movie-details-client' d.movie_id %}"
                                                  title="Zobacz szczególy filmu oraz zwiastun!"> <img
                                    src={{ d.thumbnail.url }}
                                            width="240"
                                    height="240"></a>
                            </div>
                            <br>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}

            <h2>W najbliższe dni gramy:</h2>
            <br>
            <div class="row">
                <div class="col-md-4">
                    {% for i in future %}
                        <div class="row">
                            <div class="col-6"><a href="{% url 'movie-details-client' i.movie_id %}"
                                                  title="Zobacz szczególy filmu oraz zwiastun!"> <img
                                    src={{ i.thumbnail.url }}
                                            width="240"
                                    height="240"></a>
                            </div>
                            <br>

                        </div>
                    {% endfor %}
                </div>
            </div>
            </div>

        </div>
    {% else %}
        <h3>Obecnie nie wyświetlamy żadych filmów.</h3>
    {% endif %}
{% endblock %}

client/templates/client/kontakt.html
{% extends 'client/base.html' %}
{% block head %}
    <title>Kontakt</title>
        <style>
        body {

            min-height: 100%;
        }
        .container-card {
            margin-top: 100px;
            margin-bottom: 200px;
            padding-bottom: 10px;
            margin-left: 300px;
            margin-right: 300px;
            opacity: 90%;
        }

        h2.formularz {
            color: darkslategrey;
            font-size: x-large;
            text-align: center;
            margin-top: 6%;
            letter-spacing: 10px;
        }

        a {
            text-decoration: none;
            color: grey;
        }

        a:hover {
            color: #fff;
        }

        h1 {
            text-align: center;
            color: white;
            letter-spacing: 5px;
            font-family:"Nova Round";
        }
    </style>
{% endblock %}
{% block logo-text %}
    <h1 class="logo-text">Kontakt</h1>
{% endblock %}
{% block content %}
    <div class="container-card" >
    <div class="card" style="height:700px ;background: darkgray;box-shadow:0 10px 6px -6px black ">
    <div class="card-body">
    <h2 class="formularz">
        <span>
            Adres: <br>
            <h1 class="font-weight-light"> Wyższa Szkoła Bankowa </h1> <br>
            Fabryczna 29/31, 53-609 Wrocław <br> <br>
            Telefon: <br>
            <h1 class="font-weight-light">  123456789 <br> <br> </h1>
            E-mail: <br>
              <h1 class="font-weight-light">  kino@gmail.com <br> <br> </h1>
            Strona WWW: <br>
              <h1 class="font-weight-light"> www.link.pl </h1>
            <div style="height:600px"></div>
        </span>
    </h2>
    </div>
    </div>
</div>
{% endblock %}

client/templates/client/podsumowanie.html
{% extends 'client/base.html' %}

{% block content %}
    {% if taken|length < 1 %}
        <h2>Nie wybrano typów biletów!</h2>
    {% elif taken|length > 10 %}
        <h2>Możesz zarezerwowoać maksymalnie 10 miejesc!</h2>
    {% else %}
        <div class="jumbotron jumbotron-fluid" style="opacity: 85%">
  <div class="container" style="font-family: 'Lucida Grande', 'Lucida Sans Unicode', 'Geneva', 'Verdana', sans-serif">
        <h3 class="display-4">Podsumowanie</h3>
        <form action="" method="post">
            {% csrf_token %}
            <table>
                <tr class="table-secondary">
                    <td>Seans  :</td>
                    <td>{{ showtime }}</td>
                </tr>
                <tr class="table-secondary">
                    <td>Imię  : </td>
                    <td>{{ client_initial.first_name }}</td>
                </tr>
                <tr class="table-secondary">
                    <td>Nazwisko  : </td>
                    <td> {{ client_initial.last_name }}</td>
                </tr>
                <tr class="table-secondary">
                    <td>Email  :</td>
                    <td> {{ client_initial.email }}</td>
                </tr>
                <tr class="table-secondary">
                    <td>Numer telefonu   :</td>
                    <td> {{ client_initial.phone_number }}</td>
                </tr>
            </table>
            <br>
            <table class="table table-striped">
            <tbody>
                {{ ticket_form.management_form }}
                {% for form in ticket_form %}
                    Miejsce: {{ form.seat_id.data }}<br>
                    {% for i in db_ticket_types %}
                        {% if i.ticket_id|lower == form.tickettype_id.data|lower %}
                            Typ biletu: {{ i.type }}{{ form.as_p }}
                        {% endif %}
                    {% endfor %}
                {% endfor %}
            </tbody>
            </table>
            <b>Do zapłaty: {{ total }} PLN</b>
            {{ client_form }}
            {{ reservation_form }}<br><br>
            <input class="btn-lg btn-info" type="submit" value="Zarezerwuj"/>
        </form>
  </div>
        </div>
    {% endif %}
{% endblock %}

client/templates/client/repertuar.html
{% extends 'client/base.html' %}
{% block head %}
    <style>
        table, th, td {
            border: 1px solid ;

        }
    </style>
{% endblock %}
{% block logo-text %}
    <h1 class="logo-text">Repertuar</h1>
{% endblock %}

{#https://stackoverflow.com/questions/8678336/django-grouping-querysets-by-a-certain-field-in-template#}
{% block content %}
  {% if showtime_list|length > 0 %}
        {% regroup showtime_list by start_date|date:"d.m.Y" as showtime_by_date %}
        <table class="table table-striped table-dark">
            {% for showtime in showtime_by_date %}
                <tr>
                    <th colspan="3" style="text-align: center">{{ showtime.grouper }}</th>
                </tr>
                <thead>
                <tr>
                    <th scope="col">Tytuł</th>
                    <th scope="col">Godzina rozpoczęcia</th>
                    <th scope="col">Godzina zakończenia</th>
                </tr>
                </thead>
                <tbody>
                {% for i in showtime.list %}
                    <tr>
                   <td>{{ i.movie_id.title|title }} </td>
                     <td>{{ i.start_date|date:"H:i" }} </td>
                   <td>{{ i.end_date|date:"H:i" }} </td>
                    <td><a class="btn btn-info" href="{% url 'reservation-form-client' i.showtime_id %}" role="button">Zarezerwuj miejsce</a></td></tr>
                {% endfor %}

            {% endfor %}
        </tbody>
        </table>
    {% else %}
        <h3>Obecnie nie wyświetlamy żadych filmów.</h3>
    {% endif %}
{% endblock %}